### PR TITLE
Add policy check

### PR DESCRIPTION
**Pull request by bolkedebruin**
Adds policy check, still needs resource config.

Please review on scala style ;-)

@nielsdenissen

### CODE REVIEW

**Review by arempter — COMMENTED** [review]
we should vals instead of vars as much as possible

**Comment by nielsdenissen** [comment]
Since we need to make more changes to the structure of this project and will have to walk through all code currently there, we'll merge in this change and modify it in the process after. If you want we can show you what changes we made to the Scala class after @bolkedebruin ;)

**Review by nielsdenissen — COMMENTED** [review]
Some changes need to be done to the Scala class as it is written in a very Java-like fashion. Since we'll need to walk through the project and restructure anyway, we'll do this after the merge.

**Review by nielsdenissen — APPROVED** [review]
Some changes need to be done to the Scala class as it is written in a very Java-like fashion. Since we'll need to walk through the project and restructure anyway, we'll do this after the merge.

**Pull request merged**
